title = "UDIA"
description = "Experimenter, scientist, software developer. Collection of content pertaining to UDIA."
baseURL = "//udia.ca/"
languageCode = "en-us"
copyright = "Creative Rights 4.0"

theme = "candor"
#theme = "candor-dev"
pygmentsCodefences = true
pygmentsStyle = "colorful"
enableGitInfo = true
enableRobotsTXT = true

[params]
  author = "Alexander Wong"
  license = "Creative Commons Attribution-NonCommercial 4.0 International License"
  licenseLink = "https://creativecommons.org/licenses/by-nc/4.0/"

[taxonomies]
  category = "categories"
  status = "status"
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1

[menu]
[[menu.main]]
  name="home"
  url="//"
  weight=100
[[menu.main]]
  name="about"
  url="/posts/about/"
  weight=110
