title = "UDIA"
description = "Experimenter, scientist, software developer. Collection of content pertaining to UDIA."
baseURL = "https://udia.ca/"
languageCode = "en-us"
copyright = "Creative Commons Attribution-NonCommercial 4.0 International License"

theme = "candor"
#theme = "candor-dev"
pygmentsCodefences = true
pygmentsStyle = "colorful"
enableGitInfo = true
enableRobotsTXT = true

[params]
  author = "Alexander Wong"
  license = "Creative Commons Attribution-NonCommercial 4.0 International License"
  licenseLink = "https://creativecommons.org/licenses/by-nc/4.0/"
  disableKatexJS = false
  # disableKatexJS = true # broken in latest stable Hugo version

[taxonomies]
  category = "categories"
  status = "status"
  tag = "tags"

[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      # katex = true # broken in latest stable Hugo version
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xHTML = false
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 1

[menu]
[[menu.main]]
  name="home"
  url="//"
  weight=100
[[menu.main]]
  name="about"
  url="/about/"
  weight=110
[[menu.main]]
  name="posts"
  url="/posts/"
  weight=120
