baseURL = "//udia.ca/"
languageCode = "en-us"
title = "Alexander Wong"
# theme = "candor"
theme = "candor-dev"
pygmentsCodefences = true
pygmentsStyle = "swapoff"
enableGitInfo = true

[taxonomies]
  category = "categories"
  status = "status"
  tag = "tags"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1

[menu]
[[menu.main]]
  name="home"
  url="//"
  weight=100
[[menu.main]]
  name="about"
  url="/posts/about/"
  weight=110
